### ISSUE TITLE
Some changes would be nessesary to run. 

### ISSUE THREAD

**Issue by farhadi76m** [jan-ackermann/Maskomaly#1]
Hello, and thank you for sharing this GitHub code! I gave it a try in Google Colab and ran into a few issues that might be helpful for everyone:

1. In `compute_ood.py`, there was an error with `args.output` . Adding default parameters could resolve this issue.

2. In `defaults.py` within Detectron2, consider importing hooks as follows: from `detectron2.engine import hooks` instead of `from ... import hooks.`
3. It would be helpful to mention the pretrained files. You can acquire them using these commands:
```
!wget https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_large_patch4_window12_384_22k.pth
!python /content/Mask2Former/tools/convert-pretrained-swin-model-to-d2.py swin_large_patch4_window12_384_22k.pth swin_large_patch4_window12_384_22k.pkl
```

Thank you for your work, and I hope these suggestions are helpful for users! 👍

**Comment by jan-ackermann** [comment]
Hello, 
thank you for your help! I will have a look into it over the weekend :)
