### ISSUE TITLE
Some problems about the output results 

### ISSUE THREAD

**Issue by ZelongZeng** [jan-ackermann/Maskomaly#3]
Hi, 
Thank you very much for your nice paper and sharing code! 
I meet two problems when I try to output the result. 

**1.** When I follow the guidelines and try to output the result, but I cannot get food result. 
<img width="640" alt="image" src="https://github.com/jan-ackermann/Maskomaly/assets/40358919/361b0278-9d9f-4f58-99bc-bf25576853e5">
<img width="640" alt="image" src="https://github.com/jan-ackermann/Maskomaly/assets/40358919/f4fc0da4-1400-47a5-bf1d-bdc56414b334">

I found a similar post in the issues, but I don't know how to solve it. 

**2.** I found that the running is slow. In my machine, each image needs 34s for computing the ood and 25s for evaluate the ood. I'm not sure if this is normal? 

Could you help me to solve the problem? Thank you very much.

**Comment by jan-ackermann** [comment]
Hey, yes that does not look correct.

I have observed that it does not work for some other people but I am not sure why. Right now, I don't have much time to look into it, probably in 2 weeks.

But, I can offer to send you the colab that someone else used to fix it for him. Just drop me an email.
