### ISSUE TITLE
Inquiry Regarding Poor Performance of Reproduced Code Results

### ISSUE THREAD

**Issue by HuiyuW** [jan-ackermann/Maskomaly#4]
Hello,

I am currently working on reproducing your code. I have thoroughly gone through your provided codebase and attempted to replicate the experimental results as presented in the paper.

However, I have encountered significant discrepancies between the expected results outlined in the paper and the outcomes obtained from running the provided code. The test performance appears to be considerably subpar.

Could you please verify whether I have correctly followed the implementation steps outlined in your code repository?
Moreover, I am eager to understand the reasons behind the observed differences in results and any potential insights you may have regarding this matter.

I have attached the relevant code snippets and results to this issue for your reference. Your expertise and guidance would be immensely valuable in resolving these discrepancies.

```
!python3 compute_ood.py --config-file /content/Mask2Former/configs/cityscapes/instance-segmentation/maskformer2_R101_bs16_90k.yaml --input /content/dataset_AnomalyTrack --dataset smiyc_anomaly --output ./output/smiyc_anomaly --opts MODEL.WEIGHTS /content/SWIN-L.pkl

!python3 evaluate_ood.py --input ./output/smiyc_anomaly --dataset smiyc_anomaly --output ./results/smiyc_anomaly
```

SWIN-L.pkl is downloaded from here "https://github.com/facebookresearch/Mask2Former/blob/main/MODEL_ZOO.md"
with link "https://dl.fbaipublicfiles.com/maskformer/mask2former/cityscapes/semantic/maskformer2_swin_large_IN21k_384_bs16_90k/model_final_17c1ee.pkl".

![000_anomaly](https://github.com/jan-ackermann/Maskomaly/assets/86197816/9d0630c5-26e3-41fc-8670-fa6306bff5a2)
![000_heat](https://github.com/jan-ackermann/Maskomaly/assets/86197816/4e6dfc4c-1b20-4658-b462-5df413dadec3)
![001_anomaly](https://github.com/jan-ackermann/Maskomaly/assets/86197816/bfe094f7-7f2f-4c80-8278-049d14a8f56a)
![001_heat](https://github.com/jan-ackermann/Maskomaly/assets/86197816/6af0e99a-ee59-4cc2-a280-638132fdc36e)
![004_anomaly](https://github.com/jan-ackermann/Maskomaly/assets/86197816/e935b688-2fde-4032-92ab-985ae29d1842)
![004_heat](https://github.com/jan-ackermann/Maskomaly/assets/86197816/e2d773fd-9687-4f42-b262-220697ce4e4f)
![007_anomaly](https://github.com/jan-ackermann/Maskomaly/assets/86197816/63c34664-bd40-4f4d-93cf-7d97f058097d)
![007_heat](https://github.com/jan-ackermann/Maskomaly/assets/86197816/64d477dd-a51c-4958-bb73-e4bf3baafe53)
![009_anomaly](https://github.com/jan-ackermann/Maskomaly/assets/86197816/8b89e530-bc39-46a9-8629-2e66cd6b1183)
![009_heat](https://github.com/jan-ackermann/Maskomaly/assets/86197816/4b628cfb-f024-49a8-803a-34da192ec67f)

**The average precision is: 14.781%
The auroc is: 49.79%
The fpr is: 97.25%
The aupr is: 14.76%**

Additionally, I've identified a few potential errors in your code.

Maskomaly/maskomaly/evaluate_ood.py

line66:  

`if i % args.logging_interval == 0 and args.datset != 'smiyc_full':`

Thank you for your time and consideration. I look forward to your response.

Best regards

**Comment by jan-ackermann** [comment]
Hey, this indeed looks very weird! Some other people have pointed out that it does not work as expected on their system. Unfortunately, I currently don't have much time to look into it. But someone told me they got it running in a Colab. I will add a link to that colab in the README. Otherwise, I tested the docker and this should be platform independent and work for you!
