### ISSUE TITLE
Performance Discrepancy When Replicating Results On FishyScapes Static

### ISSUE THREAD

**Issue by xiaoran-roosevelt** [jan-ackermann/Maskomaly#6]
Hi, I would like to thank you for your remarkable work and for sharing the codebase of your paper. It has been very insightful and helpful for my research.

I am writing to report an issue regarding replicating the results as presented in your paper. Despite closely following the instructions and environment setup as described in your documentation, I observed a noticeable difference in performance metrics.

When running Swin-L on smiyc anomaly validation dataset, i can get a nice result,as shown in follow pictures.
![image](https://github.com/jan-ackermann/Maskomaly/assets/48651387/5ffeed21-a340-4a04-931f-c5769e4f5c56)
![image](https://github.com/jan-ackermann/Maskomaly/assets/48651387/c37eea6e-e04b-4538-b6fc-7d067949a325)
![image](https://github.com/jan-ackermann/Maskomaly/assets/48651387/80544de4-86bd-49d0-8d8b-ba327c2588f8)
![image](https://github.com/jan-ackermann/Maskomaly/assets/48651387/c062c3ac-4e44-437a-b3b3-08e644d02296)
![image](https://github.com/jan-ackermann/Maskomaly/assets/48651387/0a9ab818-7f48-46c8-adf4-e1471b8fc882)

Without making any changes to the code，i run Swin-L on Fishyscapes static v2 validation dataset,i am unable to replicate the results reported in the paper, or achieve results that are comparable to them.As shown in follow pictures.
![image](https://github.com/jan-ackermann/Maskomaly/assets/48651387/4628e3b8-da2f-4824-8b21-456402632638)
![image](https://github.com/jan-ackermann/Maskomaly/assets/48651387/49155c55-1473-4499-b4c7-0614dcd53ae8)
![image](https://github.com/jan-ackermann/Maskomaly/assets/48651387/f57259f3-b807-41b3-9483-a48c7c314d5a)
![image](https://github.com/jan-ackermann/Maskomaly/assets/48651387/48497963-18bd-4bb5-bf36-14db49847567)

The pre-trained model weights are provided by Mask2Former, and I simply made a modification to the name, changing it to 'model_final.pkl'.
I am wondering if there might be any additional configurations or steps that were not mentioned in the documentation but are crucial to achieving the reported results. Or perhaps, if there have been updates or corrections to the codebase or methodology post-publication?

Any insights or suggestions you could provide would be greatly appreciated. Thank you for your time and consideration.

**Comment by jan-ackermann** [comment]
Hi,
Thank you for reaching out! I can not tell you what the problem is from the results. 
Have you downloaded the data from the google drive link that I have provided? (Just to make sure there was no mistake during the creation of the dataset)
I have cleaned up the code base for easier use but have not changed the method.
Additionally, you might want to try out the Docker. I verified that each experiment's results aligned with the reported results before uploading to docker hub.
Let me know If there is anything else or you have a more specific idea of what the problem could be!

**Comment by xiaoran-roosevelt** [comment]
> Hi, Thank you for reaching out! I can not tell you what the problem is from the results. Have you downloaded the data from the google drive link that I have provided? (Just to make sure there was no mistake during the creation of the dataset) I have cleaned up the code base for easier use but have not changed the method. Additionally, you might want to try out the Docker. I verified that each experiment's results aligned with the reported results before uploading to docker hub. Let me know If there is anything else or you have a more specific idea of what the problem could be!

yes,i downloaded the fs static dataset from google driver link which you provided.

**Comment by jan-ackermann** [comment]
Thanks for clarifying. Have you had the chance to try the docker image? If I understood that correctly, others have found that the mask2former gives different outputs in a different environment. Some found solutions for their cases, but I must admit that I am clueless as to why it behaves like this.

**Comment by chrisyan** [comment]
Hi Jan, thanks for your amazing work!. I reproduced your code and get the results. I report the results on RoadAnomaly and FS static.  

RoadAnomaly with FPR 90:  
The average precision is: 73.188%
The auroc is: 94.89%
The fpr is: 11.33%
The aupr is: 73.19%

RoadAnomaly with FPR 95:  
The average precision is: 73.188%
The auroc is: 94.89%
The fpr is: 28.87%
The aupr is: 73.19%

FS Static with FPR 90:  
The average precision is: 53.063%
The auroc is: 94.13%
The fpr is: 14.41%
The aupr is: 53.06%

FS Static with FPR 95:  
The average precision is: 53.063%
The auroc is: 94.13%
The fpr is: 40.85%
The aupr is: 53.06%

The results are not very consistent with the value in the paper. Also, what I'm asking is in the paper, on both datasets, do you report FPR90 or FPR95? Thank you so much!

**Comment by jan-ackermann** [comment]
Hi,
Thank you for your comment and interest in our work.
All of our numbers are FPR95 and before submission to BMVC, I double checked the numbers by using FishyScapes local evaluation script as well.

I am aware that there are platform based differences in this code base. After receiving first comments on these inconsistencies I published a Docker container with my original code and FishyScapes evaluation script which on my 
Ubuntu 22.04 + RTX 4080 + CUDA 11.7 led to the results reported in the paper.

Unfortunately, even within a docker environment the results change on different platforms.
I do not know why this is the case :(

I still hope that you find our training-free idea interesting and helpful!
